##
## Makefile for vector in /home/arbona/libs/vector
##
## Made by Thomas ARBONA
## Login   <thomas.arbona@epitech.eu>
##
## Started on  Mon Feb 27 19:41:55 2017 Thomas ARBONA
## Last update Fri Mar 24 13:48:55 2017 John Doe
##

all:
		make -C vector/
		make -C my/

clean:
		make clean -C vector/
		make clean -C my/

fclean:
		make fclean -C vector/
		make fclean -C my/

re:
		make re -C vector/
		make re -C my/
