#!/bin/bash

# Apt update
sudo apt update
sudo apt upgrade
echo -e "\033[0;32mCan you, please, say yes when apt-get will ask you if you want to continue ? You forgot last time...\033[0;0m"
sudo apt install libmount-dev libffi-dev libcanberra-gtk-module:i386 libgtk-3-dev
sudo apt install libgl1-mesa-dev libglu1-mesa-dev
sudo apt install libglew-dev
